---
- name: Create my directory
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
  - name: Create directory if it does not exist
    file:
      path: /etc/my-directory
      state: directory
      mode: '0755'
